CUS1166_Project_Template-master/app/models.py
#from flask import url_for
from app import db

class Appointment(db.model):


    appointment_id = db.Column(db.Integer, primary_key=True)
    appointment_title = db.Column(db.Title, index=True)
    appointment_date = db.Column(db.Date, index=True)
    appointment_time = db.Column(db.Time, index=True)
    location_address = db.Column(db.Adress, index=True)
    customer_name = db.Column(db.Name, index=True)
    appointment_status = db.Column(db.String(128))

class Task(db.Model):

    task_id = db.Column(db.Integer, primary_key=True)
    task_desc = db.Column(db.String(128), index=True)
    task_status = db.Column(db.String(128))

CUS1166_Project_Template-master/app/main/forms.py
# import flask_wtf
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, DateField, TimeField, TextAreaField
from wtforms.validators import ValidationError, DataRequired, Length


class TaskForm(FlaskForm):
    task_desc = StringField('task_desc', validators=[DataRequired()])
    task_status_completed = SelectField('Status', choices=[('todo','Todo'),('doing','Doing'),('done','Done')])
    submit = SubmitField('submit')

class Appointment(FlaskForm):
    appointment_title = StringField('Title', validators=[DataRequired()])
    appointment_date = DateField('Date (year-month-date)', validators=[DataRequired()])
    start_time = TimeField('Start Time', validators=[DataRequired()])
    location = StringField('Address', validators=[DataRequired()])
    customer_name = StringField('Name', validators=[DataRequired()])
    notes = StringField('Note', validators=[DataRequired()])
    appointment_status_completed = SelectField('Status', choices=[('todo','Todo'),('doing','Doing'),('done','Done')])
    submit = SubmitField('submit')

CUS1166_Project_Template-master/app.py
from app import create_app

app = create_app()

CUS1166_Project_Template-master/app/__init__.py
from flask import Flask, current_app
#
from app import models
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap

## from flask_migrate  import Migrate
## from flask_login import LoginManager

# Instanciate modules used in the project.

db = SQLAlchemy()

## migrate = Migrate()
## login = LoginManager()


def create_app(config_class=Config):

    app = Flask(__name__)

    # load configuration parameters from Config class
    app.config.from_object(config_class)

    # Initialize app for db and migrate modules.
    db.init_app(app)
    bootstrap = Bootstrap(app)
    ##migrate.init_app(app,db)
    ##login.init_app(app)


    # Added the autho blueprint
    ##from app.auth import bp as auth_routes_bp
    ##app.register_blueprint(auth_routes_bp,url_prefix='/auth')


    # Added the main app.
    from app.main import bp as main_routes_bp
    app.register_blueprint(main_routes_bp)
    return app;

CUS1166_Project_Template-master/app/main/__init__.py
# Imports the Blueprint class from flask.
from flask import Blueprint

bp = Blueprint('main',__name__)

from app.main import routes

CUS1166_Project_Template-master/app/main/routes.py
from flask import render_template,  redirect, url_for
from app.main import bp
from app import db
from app.main.forms import TaskForm, Appointment
from app.models import Task, Appointment

# Main route of the applicaitons.
@bp.route('/', methods=['GET','POST'])
def index():
    return render_template("main/index.html")


#
#  Route for viewing and adding new tasks.
@bp.route('/todolist', methods=['GET','POST'])
def todolist():
    form = TaskForm()

    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.
        new_task = Task()
        new_task.task_desc = form.task_desc.data
        new_task.task_status = form.task_status_completed.data

        db.session.add(new_task)
        db.session.commit()

        # Redirect to this handler - but without form submitted - gets a clear form.
        return redirect(url_for('main.todolist'))

    todo_list = db.session.query(Task).all()

    return render_template("main/todolist.html",todo_list = todo_list,form= form)


#
# Route for removing a task
@bp.route('/todolist/remove/<int:task_id>', methods=['GET','POST'])
def remove_task(task_id):

    # Query database, remove items
    Task.query.filter(Task.task_id == task_id).delete()
    db.session.commit()

    return redirect(url_for('main.todolist'))


#
# Route for editing a task

@bp.route('/todolist/edit/<int:task_id>', methods=['GET','POST'])
def edit_task(task_id):
    form = TaskForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        # Get the data from the form, and add it to the database.

        current_task = Task.query.filter_by(task_id=task_id).first_or_404()
        current_task.task_desc =  form.task_desc.data
        current_task.task_status = form.task_status_completed.data

        db.session.add(current_task)
        db.session.commit()
        # After editing, redirect to the view page.
        return redirect(url_for('main.todolist'))

    # get task for the database.
    current_task = Task.query.filter_by(task_id=task_id).first_or_404()

    # update the form model in order to populate the html form.
    form.task_desc.data =     current_task.task_desc
    form.task_status_completed.data = current_task.task_status

    return render_template("main/todolist_edit_view.html",form=form, task_id = task_id)


@bp.route('/CreateAppointment', methods=['GET', 'POST'])
def Appointment():
    form = Appointment()

    if form.validate_on_submit():
        new_appointment = Appointment()

        new_appointment.appointment_title = form.appointment_title.data
        new_appointment.appointment_date = form.appointment_date.data
        new_appointment.appointment_time = form.appointment_time.data
        new_appointment.location_address = form.location_address.data
        new_appointment.customer_name = form.customer_name.data
        new_appointment.appointment_status = form.appointment_status_completed.data

        db.session.add(new_appointment)
        db.session.commit()

        return redirect(url_for('main.appointment'))


    appointment_list = db.session.query(Appointment).all()

    return render_template("main/appointmentlist.html",todo_list = appointment_list,form= form)


bp.route('/appointmentlist/edit/<int:appointment_id>', methods=['GET','POST'])
def edit_Appointment(appointment_id):
    form = Appointment()
    print(form.validate_on_submit())
    if form.validate_on_submit():

        current_appointment = Appointment.query.filter_by(appointment_id=appointment_id).first_or_404()
        current_appointment.appointment_title = form.appointment_title.data
        current_appointment.appointment_date = form.appointment_date.data
        current_appointment.appointment_time = form.appointment_time.data
        current_appointment.location_address = form.location_address.data
        current_appointment.customer_name = form.customer_name.data
        current_appointment.appointment_status = form.appointment_status_completed.data


        db.session.add(current_appointment)
        db.session.commit()
        # After editing, redirect to the view page.
        return redirect(url_for('main.appointment'))

    current_appointment = Appointment.query.filter_by(appointment_id=appointment_id).first_or_404()

    form.appointment_title.data = current_appointment.appointment_title
    form.appointment_date.data = current_appointment.appointment_date
    form.appointment_time.data = current_appointment.appointment_time
    form.location_address.data = current_appointment.location_address
    form.customer_name.data = current_appointment.customer_name


    return render_template("main/appointment_edit_view.html",form=form, appointment_id = appointment_id)

@bp.route('/Appointment/remove/<int:appointment_id>', methods=['GET','POST'])
def delete_appointment(appointment_id):


    Appointment.query.filter(Appointment.appointment_id == appointment_id).delete()
    db.session.commit()

    return redirect(url_for('main.appointment'))


#

CUS1166_Project_Template-master/app/templates/layout.html
{% extends "bootstrap/base.html" %}
{% block metas %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="Individual Project Template for CUS 1166">
  <meta name="author" content="Christoforos Christoforou">
{% endblock  %}

{% block title %}
  CUS 1166 - Individual or Group Project Template
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/cus1166_custom.css')}}">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
{% endblock %}


{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">CUS1166 Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      {%  block menuitems %}

      {%  endblock menuitems%}
    </ul>
    </div>
</nav>
{% endblock %}

{% block content %}
    {% block main_content %}
    {% endblock main_content %}
      {% block footer %}
      <!-- Footer -->
      <footer class="page-footer font-small blue fixed-bottom">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2019 Copyright:
          <a href="https://www.researchgate.net/profile/Christoforos_Christoforou"> Template project for CUS1166 by Dr. Christoforos Christoforou</a>
        </div>
        <!-- Copyright -->

      </footer>
      <!-- Footer -->
      {% endblock footer %}
{% endblock content%}

CUS1166_Project_Template-master/app/templates/main/appointment.html
{% extends "menu.html" %}

{% block main_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Appointment List</h4>
                        <form method="POST" action="{{url_for('main.Appointment')}}" >

                        <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.appointment_title(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_date(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_time(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.location_address(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.customer_name(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_status_completed }}
                                <button class="add btn btn-primary font-weight-bold appointment-list-add-btn">Add</button>
                       </div>
                     </form>

                       <!-- Show current tasks if avaiblae -->
                        <div class="list-wrapper">
                            <ul class="d-flex flex-column-reverse todo-list">
                             {% for appointments in appointment %}

                                {% if 'done' == appointment.task_status%}
                                    <li class="completed">
                                {% else %}
                                    <li>
                                {% endif %}
                                    <a href="{{url_for('main.edit_appointment',appointment_id=appointment.appointment_id)}}">
                                         <i class="fas fa-edit"></i>
                                    </a>

                                    <div class="form-check">

                                      <label class="form-check-label">
                                          {% if 'done' == appointment.appointment_status %}
                                            {{appointment.appointment_title}} - <span class="badge badge-success">{{appointment.appointment_status}}</span>
                                          {% elif 'doing' == task.task_status %}
                                            {{appointment.appointment_title}} - <span class="badge badge-warning">{{appointment.appointment_status}}</span>
                                          {% elif 'todo' == task.task_status %}
                                             {{appointment.appointment_title}} - <span class="badge badge-danger">{{appointment.appointment_status}}</span>
                                          {% endif %}
                                            <i class="input-helper"></i>
                                      </label>
                                    </div>
                                    <a href="{{url_for('main.delete_appointment',appointment_id=appointment.appointment_id)}}" class="remove"><i class="fas fa-times"></i></a>
                              </li>
                             {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/appointment_edit_view.html
{% extends "menu.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Appointment List</h4>
                        <form method="POST" action="{{url_for('main.edit_appointment',appointment_id=appointment_id)}}" >
                            <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.appointment_title(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_date(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_time(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.location_address(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.customer_name(class_='form-control appointment-list-input', placeholder='What do you need to do today?')}}
                                {{ form.appointment_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/index.html
{% extends "menu.html" %}

{% block main_content %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="mt-5">Individual Project for CUS1166 -</h1>
      <p class="lead">Get ready to showcase your Software Engineering Skills!</p>
      <ul class="list-unstyled">
        <li> Applying agile methodoloies in software development </li>
        <li>Realizing a full sprint implementing use-case  </li>
        <li> Using Flask, ORMs, Forms to implement new features </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/todolist.html
{% extends "menu.html" %}

{% block main_content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.todolist')}}" >

                        <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>

                       <!-- Show current tasks if avaiblae -->
                        <div class="list-wrapper">
                            <ul class="d-flex flex-column-reverse todo-list">
                             {% for task in todo_list %}

                                {% if 'done' == task.task_status%}
                                    <li class="completed">
                                {% else %}
                                    <li>
                                {% endif %}
                                    <a href="{{url_for('main.edit_task',task_id=task.task_id)}}">
                                         <i class="fas fa-edit"></i>
                                    </a>

                                    <div class="form-check">

                                      <label class="form-check-label">
                                          {% if 'done' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-success">{{task.task_status}}</span>
                                          {% elif 'doing' == task.task_status %}
                                            {{task.task_desc}} - <span class="badge badge-warning">{{task.task_status}}</span>
                                          {% elif 'todo' == task.task_status %}
                                             {{task.task_desc}} - <span class="badge badge-danger">{{task.task_status}}</span>
                                          {% endif %}
                                            <i class="input-helper"></i>
                                      </label>
                                    </div>
                                    <a href="{{url_for('main.remove_task',task_id=task.task_id)}}" class="remove"><i class="fas fa-times"></i></a>
                              </li>
                             {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/main/todolist_edit_view.html
{% extends "menu.html" %}

{% block content %}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="card px-3">
                    <div class="card-body">
                        <h4 class="card-title">CUS1166 - Todo List</h4>
                        <form method="POST" action="{{url_for('main.edit_task',task_id=task_id)}}" >
                            <div class="add-items d-flex">
                                <!-- csrf_token is required to validate the form -->
                                {{ form.csrf_token }}
                                {{ form.task_desc(class_='form-control todo-list-input', placeholder='What do you need to do today?')}}
                                {{ form.task_status_completed }}
                                <button class="add btn btn-primary font-weight-bold todo-list-add-btn">Add</button>
                       </div>
                     </form>
                   </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

CUS1166_Project_Template-master/app/templates/menu.html
{% extends "layout.html" %}
{%  block menuitems %}
<li class="nav-item active">
  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.todolist')}}">Sample Use Case</a>
</li>
{%  endblock %}